---
- name: Generate list of packages to operate on
  set_fact:
    _aur_packages: "{{ _base_install | map('extract', _base_packages['aur']) | flatten }}"
    _repo_packages: "{{ _base_install | map('extract', _base_packages['repo']) | flatten }}"

- name: install aur packages
  become: false
  aur:
    skip_installed: true
    name: "{{ _aur_packages }}"

- name: Replace iptables with iptables-nft
  shell: |
    yes|pacman -Su iptables-nft

- name: install base packages
  pacman:
    name: "{{ _repo_packages }}"
    state: present
    extra_args: --noconfirm

- name: Configure root
  user:
    name: root
    shell: '{{ shell }}'

- name: set timezone
  shell: timedatectl set-timezone America/New_York

- name: set ntp
  shell: timedatectl set-ntp true
