---
- name: install base packages
  pacman:
    name:
      - ttf-hack
      - noto-fonts
      - bc
      - wget
      - openssh
      - jq
      - most
      - fzf
      - rsync
      - git
      - vi
      - man
      - neovim
      - screen
      - tree
      - htop
      - nmap
      - nethogs
      - iotop
      - openbsd-netcat
      - tcpdump
      - whois
      - ncdu
      - asciinema
      - speedtest-cli
      - rclone
      - neofetch
      - unzip
      - stress
      - bind-tools
      - cifs-utils
      - fish
      - weechat
      - words
      - fwupd
      - compsize
      - shellcheck
      - oath-toolkit
    state: present

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'

- name: set timezone
  shell: timedatectl set-timezone Europe/Paris

- name: set ntp
  shell: timedatectl set-ntp true
