---
- name: Generate list of packages to operate on
  set_fact:
    _aur_packages: "{{ _base_install | map('extract', _base_packages['aur']) | flatten }}"
    _repo_packages: "{{ _base_install | map('extract', _base_packages['repo']) | flatten }}"

- name: Install base system packages
  include_tasks: install.yml
  tags: install

- name: Remove base system packages
  include_tasks: remove.yml
  tags: remove


