---
- name: install base packages
  pacman:
    name:
      - ttf-hack
      - bc
      - wget
      - jq
      - most
      - fzf
      - rsync
      - git
      - neovim
      - screen
      - tree
      - htop
      - nmap
      - nethogs
      - openbsd-netcat
      - tcpdump
      - whois
      - ncdu
      - asciinema
      - speedtest-cli
      - rclone
      - neofetch
      - unzip
      - stress
      - bind-tools
      - cifs-utils
      - fish
      - weechat
    state: present

- name: install system packages
  pacman:
    name:
      - linux-headers
      - 
    state: present
