---
- name: Generate list of packages to operate on
  set_fact:
    _aur_packages: "{{ _remove | map('extract', _packages['aur']) | flatten }}"
    _repo_packages: "{{ _remove | map('extract', _packages['repo']) | flatten }}"

- name: Remove packages
  pacman:
    name: "{{ _repo_packages + _aur_packages }}"
    state: absent
    extra_args: --noconfirm --cascade --nosave

- name: Find unused dependencies
  command: pacman -Qdtq
  register: _unused

- name: Remove unused dependencies
  pacman:
    name: "{{ _unused.stdout_lines }}"
    state: absent
    extra_args: --recursive --nosave --noconfirm
