---
- name: install flatpak
  pacman:
    name: flatpak
    state: present
    extra_args: --noconfirm

- name: Add the flathub flatpak repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
    state: present
  loop:
    - org.freecadweb.FreeCAD

