---
###
# https://bugs.archlinux.org/task/66407
###

- name: create efi netboot dir
  file:
    path: /efi/EFI/netboot
    state: directory
    mode: '+x'

- name: Deploy ipxe-netboot
  block:
    - name: install ipxe-netboot package
      aur:
        name: ipxe-netboot
        skip_installed: true
      become: no
    - name: copy ipxe-netboot efi to efi partition
      copy:
        src: /usr/share/ipxe-netboot/ipxe.efi
        dest: /efi/EFI/netboot/
        mode: '+x'
  rescue:
    - name: Retrieve netboot efi
      get_url:
        url: https://www.archlinux.org/static/netboot/ipxe.176077d7fccb.efi
        dest: /efi/EFI/netboot/ipxe.efi

- name: install netboot.xyz
  get_url:
    url: https://boot.netboot.xyz/ipxe/netboot.xyz.efi
    dest: /efi/EFI/netboot/netboot.xyz.efi
