---
###
# https://bugs.archlinux.org/task/66407
###

- name: install ipxe-netboot
  become: no
  aur:
    name: ipxe-netboot
    skip_installed: true

- name: create efi netboot dir
  file:
    path: /efi/EFI/netboot
    state: directory

- name: copy efi netboot file
  copy:
    src: /usr/share/ipxe-netboot/ipxe.efi
    dest: /efi/EFI/netboot/

- name: create custom grub entry
  copy:
    src: 40_custom
    dest: /etc/grub.d
  notify: update grub
