---
dependencies:
  - role: aur

- name: create efi netboot dir
  file:
    path: /boot/EFI/netboot

- name: hardlink efi netboot file
  file:
    src: /usr/share/ipxe-netboot/ipxe.efi
    dest: /boot/EFI/netboot/
    state: hard

- name: create custom grub entry
  copy:
    src: 40_custom
    dest: /etc/grub.d
