---
- name: install snapper
  pacman:
    name:
      - snapper
      - snap-pac
    state: present
  notify: init btrfs grub config

- name: configure snapper
  copy:
    src: root
    dest: /etc/snapper/configs/
  notify:
    - enable grub-btrfs
    - enable timeline
    - enable cleaner

- name: activate snapper configuration
  copy:
    src: snapper
    dest: /etc/conf.d
