---

- name: create locale grub dir
  file:
    path: /boot/grub/locale
    state: directory

- name: copy fr locale grub
  copy:
    src: /usr/share/locale/fr/LC_MESSAGES/grub.mo
    dest: /boot/grub/locale/fr.gmo

- name: configure grub
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="{{cmdline}}"'
    state: present
  when: ansible_virtualization_role == "host"

- name: configure mkinitcpio
  template:
    src: mkinitcpio.j2
    dest: /etc/mkinitcpio.conf
  notify: generates initramfs
