---
- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'
    - blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist

- name: Install reflector service
  copy:
    src: reflector.service
    dest: /etc/systemd/system/
  notify: enable reflector

- name: Update lists and upgrade
  pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: --noconfirm

 # keep kernel modules dir after an upgrade
- name: Install pacman hooks
  become: no
  pacman:
    name: kernel-modules-hook
    state: present
    extra_args: --noconfirm
    update_cache: yes

- name: Enable kernel modules cleanup
  systemd:
    name: linux-modules-cleanup
    enabled: yes

- name: Install archaudit hook
  copy:
    src: arch-audit.hook
    dest: /usr/share/libalpm/hooks
