---
- name: configure pacman 1
  lineinfile:
    path: /etc/pacman.conf
    regexp: "#{{ item }}"
    line: "{{ item }}"
  with_items:
    - Color
    - UseSysLog
    - CheckSpace

- name: configure pacman 2
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#ILoveCandy'
    line: 'ILoveCandy'
    insertafter: '# Misc options'

- name: configure pacman 3
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Install reflector service
  copy:
    src: reflector.service
    dest: /etc/systemd/system/
    mode: "+x"
  notify: enable reflector

- name: Update lists and upgrade
  pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: --noconfirm

 # keep kernel modules dir after an upgrade
- name: Install pacman hooks
  become: yes
  pacman:
    name: kernel-modules-hook
    state: present
    extra_args: --noconfirm

- name: Enable kernel modules cleanup
  systemd:
    name: linux-modules-cleanup
    enabled: yes
