---
- name: copy zfs scrub systemd service
  copy:
    src: zfs-scrub.service
    dest: /etc/systemd/system/

- name: copy zfs scrub systemd timer
  copy:
    src: zfs-scrub.timer
    dest: /etc/systemd/system/
  notify: enable zfs scrub timer
