---
- name: install containers packages
  pacman:
    name:
      - docker
      - docker-compose
      - podman
  notify: restart docker

- name: copy subuid files
  copy:
    src: subuid
    dest: /etc

- name: copy subgid files
  copy:
    src: subuid
    dest: /etc
