---
- name: Get information about latest zfsbootmanager release
  uri:
    url: https://api.github.com/repos/zbm-dev/zfsbootmenu/releases/latest
    body_format: json
    creates: zbm_latest.json
    return_content: true
#    headers:
#      Accept: "application/vnd.github.v3+json"
  register: zbm_latest_response

- name: debug
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "{{ zbm_latest_response.json.assets
        | selectattr('content_type','eq','application/octet-stream')
        | flatten | map(attribute='name')}}"

- name: Create directory for zfsbootmenu
  file:
    path: "{{ _tgt_root }}/boot/efi/EFI/zfsbootmenu"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Download zfsbootmenu release
  get_url:
    dest: "{{ _tgt_root }}/boot/efi/EFI/zfsbootmenu"
    url: "{{ item }}"
    validate_certs: no
    owner: root
    group: root
    mode: '+x'
  with_items: "{{ zbm_latest_response.json.assets
    | selectattr('content_type','eq','application/octet-stream')
    | flatten
    | map(attribute='browser_download_url') }}"