---
- name: install snapper
  pacman:
    name:
      - snapper
      - snap-pac
      - grub-btrfs
    state: present
  notify: update grub

- name: configure snapper
  copy:
    src: root
    dest: /etc/snapper/configs/
    mode: '644'
  notify:
    - enable grub-btrfs
    - enable timeline
    - enable cleaner

- name: activate snapper configuration
  copy:
    src: snapper
    dest: /etc/conf.d
    mode: '644'
