---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako
      - kanshi
      - grim
      - slurp
      - wl-clipboard
      - wofi
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
    state: present

- name: install audio packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present

- name: install applications packages
  pacman:
    name:
      - alacritty
      - code
      - evince
      - firefox
      - firefox-i18n-fr
      - gimp
      - kolourpaint
      - lollypop
      - lxappearance
      - mpv
      - thunar
      - openvpn
      - playerctl
      - rdesktop
      - steam
      - transmission-gtk
      - variety
      - x2goclient
      - youtube-dl
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    - 4773BD5E130D1D45
  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - gtk-theme-minwaita #https://github.com/Alexays/Waybar/issues/515
      - connman-gtk
      - equilux-theme
      - gnome-ssh-askpass2
      - google-chrome
      - kazam
      - laptop-mode-tools
      - adb-sync-git
      - downgrade
      - lf
      - light-git
      - mindustry-git
      - minecraft-launcher
      - molotov
      - openvpn-update-systemd-resolved
      - otf-font-awesome
      - paper-icon-theme
      - pastel
      - pokerth
      - spotify
      - starleaf-breeze
      - swaylock-fancy-git
      - wdisplays-git
      #- tiny-irc-client-git
      - zoom
