---
- name: Replace iptables with iptables-nft
  command: yes y|pacman -Su iptables-nft

- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - swaylock # locker for wayland
      - swayidle
      - wdisplays # arandr for wayland
      - xorg-server-xwayland
      - waybar
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - brightnessctl # brightness manager
      - wofi # rofi for wayland
      - xdg-user-dirs
    state: present
    extra_args: --noconfirm

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-intel
      - lib32-vulkan-intel
      - intel-media-driver
      - libva-utils
    state: present
    extra_args: --noconfirm

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present
    extra_args: --noconfirm

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - evince # pdf viewer
      - okular
      - evolution # mail client
      - gnome-keyring # evolution gnome keyring
      - seahorse # keyring manager
      - kleopatra
      - firefox-esr-bin
      - flatpak # package manager
      - gimp # img editor
      - exaile
      - kolourpaint # img editor
      - shotwell # photo manager
      - digikam
      - libreoffice-still # libreoffice suite
      - lxappearance # theme manager
      - mpv # video player
      - kdenlive
      - thunar # file manager
      - tumbler # thumbnailer
      - openvpn
      - playerctl # music player cli controller
      - steam # games manager
      - transmission-gtk # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - texlive-fontsextra # latex
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - gnome-themes-extra # gtk themes
      - x2goclient 
      - youtube-dl
      - partitionmanager
      - cura
      - balena-etcher
    state: present
    extra_args: --noconfirm

- name: Create directory for nwg-shell
  become: no
  file:
    path: "/home/{{ user }}/bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '755'

- name: Set ~/bin directory to be automatically added to PATH
  blockinfile:
    path: /etc/profile
    insertafter: EOF
    block: |
      if [[ $UID -ge 1000 && -d $HOME/bin && -z $(echo $PATH | grep -o $HOME/bin) ]]
      then
        export PATH="${PATH}:$HOME/bin"
      fi

- name: Add ~/bin to PATH
  become: no
  shell: |
    if [[ $UID -ge 1000 && -d $HOME/bin && -z $(echo $PATH | grep -o $HOME/bin) ]]
    then
      export PATH="${PATH}:$HOME/bin"
    fi

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv --keyserver keyserver.ubuntu.com '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
      - equilux-theme
      - grimshot-git # grim+slurp wrapper
      - nwg-shell
      - wob # bars for wayland
      - connman-gtk # connman gtk gui
      - downgrade # package downgrader
      - lf # cli file manager
      - otf-font-awesome
      - pastel # color viewer
      - starleaf-breeze
      - swappy # screenshot editor

- name: run nwg-shell-installer
  become: no
  shell: |
    set timeout -1
    spawn nwg-shell-installer -a
    expect "Proceed? y/n "
    send -- "y\r"
    expect eof
    exit 0
  args:
    executable: /usr/bin/expect
    warn: no