---
- hosts: all
  become: yes
  roles:
    - { role: pacman, tags: pacman }
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: aur, tags: aur, become: no }
    - { role: snapper, tags: snapper }
    - { role: virtualization, tags: virtualization }
    - { role: containers, tags: containers }
  tasks:
    - name: Configure user
      user:
        name: user
        shell: /usr/bin/fish
        groups: docker,bumblebee,libvirt
        append: yes
