---
- hosts: all
  become: yes

  vars:
    user: rengo
    shell: /usr/bin/fish
    cmdline: ""

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: include guest role
      tags: guest
      include_role:
        name: guest
      when: ansible_virtualization_role == "guest"

  roles:
    - { role: pacman, tags: pacman, become: true }
    - { role: aur, tags: aur, become: true }
    - { role: zfs/systemd-boot-zectl, tags: boot, become: true }
    - { role: zfs/initramfs, tags: boot, become: true }
    - { role: zfs/systemd-scrub-trim, tags: zfs, become: true }
#   - { role: recovery, tags: recovery, become: true }
    - { role: base, tags: base, become: true }
    - { role: desktop, tags: desktop, become: true }
#    - { role: flatpak, tags: flatpak, become: true }
    - { role: cronie, tags: cronie, become: true }
    - { role: virtualization, tags: virtualization, become: true }
    - { role: containers, tags: containers, become: true }


