---
- hosts: all
  become: yes

  pre_tasks:

    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: add sudo conf for aur
      tags: always
      lineinfile:
        path: /etc/sudoers
        line: 'user ALL=(ALL) NOPASSWD: /usr/bin/pacman'

  roles:
    - { role: pacman, tags: pacman }
    - { role: aur, tags: aur }
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: snapper, tags: snapper }
    - { role: virtualization, tags: virtualization }
    - { role: containers, tags: containers }
    - { role: recovery, tags: recovery }

  tasks:
    - name: Configure user
      user:
        name: user
        shell: /usr/bin/fish
        groups: docker,bumblebee,libvirt
        append: yes

  post_tasks:

    - name: tmp size to default
      tags: always
      shell: mount -o remount,noatime /tmp
