---
- hosts: all
  roles:
    - { role: pacman, tags: pacman, become: yes }
    - { role: base, tags: base, become: yes }
    - { role: desktop, tags: desktop, become: yes }
    - { role: aur, tags: aur, become: yes }
    - { role: snapper, tags: snapper, become: yes }
    - { role: virtualization, tags: virtualization, become: yes }
    - { role: containers, tags: containers, become: yes }
  tasks:
    - name: Configure user
      user:
        name: user
        shell: /usr/bin/fish
        groups: docker,bumblebee,libvirt
        append: yes
