---
- name: install zectl
  become: no
  aur:
    name: zectl
    skip_installed: true

- name: systemd-boot loader
  copy:
    src: loader.conf
    dest: /efi/loader/

- name: systemd-boot entry
  template:
    src: org.zectl-default.j2
    dest: /efi/loader/entries/org.zectl-default.conf
