---
- name: install zrepl
  become: no
  aur:
    name: zrepl
    skip_installed: true

- name: create zrepl dir
  file:
    path: /etc/zrepl
    state: directory

- name: configure zrepl
  copy:
    src: zrepl.yml
    dest: /etc/zrepl
  notify: restart zrepl
