---
- name: install zectl
  become: no
  aur:
    name:
      - zectl-git
      - zectl-pacman-hook
    skip_installed: true

- name: set zectl bootloader
  command: zectl set bootloader=systemdboot
  changed_when: false

- name: systemd-boot loader
  copy:
    src: loader.conf
    dest: /efi/loader/
    mode: '644'

- name: systemd-boot entry
  template:
    src: org.zectl-default.j2
    dest: /efi/loader/entries/org.zectl-default.conf
    mode: '644'
