---
- name: install virt packages
  pacman:
    name:
      - qemu
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
      - ovmf
  notify: restart libvirt

- name: install podman-compose
  become: no
  aur:
    name: podman-compose
    skip_installed: true

- name: Add user to libvirt group
  user:
    name: '{{user}}'
    groups: libvirt
    append: yes

