---
- name: install virt packages
  pacman:
    name:
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
      - ovmf
  notify: restart libvirt

- name: install podman-compose
  become: no
  aur:
    name: podman-compose
    skip_installed: true

- name: Configure user
  user:
    name: {{user}}
    groups: docker,libvirt
    append: yes

