---
- name: install virt packages
  pacman:
    name:
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
  notify: restart libvirt

- name: install podman-compose
  become: no
  aur:
    name: podman-compose
    skip_installed: true
