---
- name: install virt packages
  pacman:
    name:
      - qemu
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
      - ovmf
  notify: restart libvirt

- name: Add user to libvirt group
  user:
    name: '{{user}}'
    groups: libvirt
    append: yes

